name: CustomShop
version: '1.0'
main: bgprotobg.net.customshop.CustomShop
api-version: '1.20'
commands:
  customshop:
    usage: /<command>
    description: Main command for the CustomShop plugin
    aliases: [cs]
permissions:
  customshop.give:
    description: Allows the player to give custom shop items to others
    default: op
